UPDATE team set fifaranking = 1 WHERE team = 'Germany';
UPDATE team set fifaranking = 2 WHERE team = 'Brazil';
UPDATE team set fifaranking = 3 WHERE team = 'Portugal';
UPDATE team set fifaranking = 4 WHERE team = 'Argentina';
UPDATE team set fifaranking = 5 WHERE team = 'Belgium';
UPDATE team set fifaranking = 6 WHERE team = 'Spain';
UPDATE team set fifaranking = 7 WHERE team = 'Poland';
UPDATE team set fifaranking = 8 WHERE team = 'Switzerland';
UPDATE team set fifaranking = 9 WHERE team = 'France';
UPDATE team set fifaranking = 10 WHERE team = 'Chile';
UPDATE team set fifaranking = 11 WHERE team = 'Peru';
UPDATE team set fifaranking = 12 WHERE team = 'Denmark';
UPDATE team set fifaranking = 13 WHERE team = 'Colombia';
UPDATE team set fifaranking = 14 WHERE team = 'Italy';
UPDATE team set fifaranking = 15 WHERE team = 'England';
UPDATE team set fifaranking = 16 WHERE team = 'Mexico';
UPDATE team set fifaranking = 17 WHERE team = 'Croatia';
UPDATE team set fifaranking = 18 WHERE team = 'Sweden';
UPDATE team set fifaranking = 19 WHERE team = 'Wales';
UPDATE team set fifaranking = 20 WHERE team = 'Netherlands';
UPDATE team set fifaranking = 21 WHERE team = 'Uruguay';
UPDATE team set fifaranking = 22 WHERE team = 'Iceland';
UPDATE team set fifaranking = 23 WHERE team = 'Senegal';
UPDATE team set fifaranking = 24 WHERE team = 'USA';
UPDATE team set fifaranking = 24 WHERE team = 'Northern Ireland';
UPDATE team set fifaranking = 26 WHERE team = 'Costa Rica';
UPDATE team set fifaranking = 27 WHERE team = 'Tunisia';
UPDATE team set fifaranking = 28 WHERE team = 'Slovakia';
UPDATE team set fifaranking = 29 WHERE team = 'Austria';
UPDATE team set fifaranking = 30 WHERE team = 'Paraguay';
UPDATE team set fifaranking = 31 WHERE team = 'Egypt';
UPDATE team set fifaranking = 32 WHERE team = 'Republic of Ireland';
UPDATE team set fifaranking = 32 WHERE team = 'Iran';
UPDATE team set fifaranking = 32 WHERE team = 'Scotland';
UPDATE team set fifaranking = 35 WHERE team = 'Ukraine';
UPDATE team set fifaranking = 36 WHERE team = 'Serbia';
UPDATE team set fifaranking = 37 WHERE team = 'Bosnia and Herzegovina';
UPDATE team set fifaranking = 38 WHERE team = 'Australia';
UPDATE team set fifaranking = 39 WHERE team = 'Congo DR';
UPDATE team set fifaranking = 40 WHERE team = 'Morocco';
UPDATE team set fifaranking = 41 WHERE team = 'Romania';
UPDATE team set fifaranking = 42 WHERE team = 'Turkey';
UPDATE team set fifaranking = 43 WHERE team = 'Bulgaria';
UPDATE team set fifaranking = 44 WHERE team = 'Burkina Faso';
UPDATE team set fifaranking = 45 WHERE team = 'Cameroon';
UPDATE team set fifaranking = 46 WHERE team = 'Montenegro';
UPDATE team set fifaranking = 47 WHERE team = 'Greece';
UPDATE team set fifaranking = 48 WHERE team = 'Czech Republic';
UPDATE team set fifaranking = 49 WHERE team = 'Bolivia';
UPDATE team set fifaranking = 50 WHERE team = 'Ghana';
UPDATE team set fifaranking = 51 WHERE team = 'Nigeria';
UPDATE team set fifaranking = 52 WHERE team = 'Venezuela';
UPDATE team set fifaranking = 53 WHERE team = 'Hungary';
UPDATE team set fifaranking = 54 WHERE team = 'Jamaica';
UPDATE team set fifaranking = 55 WHERE team = 'Panama';
UPDATE team set fifaranking = 56 WHERE team = 'Haiti';
UPDATE team set fifaranking = 57 WHERE team = 'Japan';
UPDATE team set fifaranking = 58 WHERE team = 'Algeria';
UPDATE team set fifaranking = 59 WHERE team = 'Norway';
UPDATE team set fifaranking = 60 WHERE team = 'South Korea';
UPDATE team set fifaranking = 62 WHERE team = 'Albania';
UPDATE team set fifaranking = 63 WHERE team = 'Saudi Arabia';
UPDATE team set fifaranking = 64 WHERE team = 'Russia';
UPDATE team set fifaranking = 65 WHERE team = 'Guinea';
UPDATE team set fifaranking = 66 WHERE team = 'Finland';
UPDATE team set fifaranking = 67 WHERE team = 'Cape Verde Islands';
UPDATE team set fifaranking = 68 WHERE team = 'Honduras';
UPDATE team set fifaranking = 69 WHERE team = 'Slovenia';
UPDATE team set fifaranking = 70 WHERE team = 'Ecuador';
UPDATE team set fifaranking = 71 WHERE team = 'China PR';
UPDATE team set fifaranking = 72 WHERE team = 'Mali';
UPDATE team set fifaranking = 73 WHERE team = 'United Arab Emirates';
UPDATE team set fifaranking = 74 WHERE team = 'Zambia';
UPDATE team set fifaranking = 75 WHERE team = 'Uganda';
UPDATE team set fifaranking = 76 WHERE team = 'FYR Macedonia';
UPDATE team set fifaranking = 77 WHERE team = 'Syria';
UPDATE team set fifaranking = 78 WHERE team = 'Uzbekistan';
UPDATE team set fifaranking = 79 WHERE team = 'Iraq';
UPDATE team set fifaranking = 80 WHERE team = 'Palestine';
UPDATE team set fifaranking = 81 WHERE team = 'South Africa';
UPDATE team set fifaranking = 82 WHERE team = 'Benin';
UPDATE team set fifaranking = 83 WHERE team = 'Luxembourg';
UPDATE team set fifaranking = 83 WHERE team = 'Curaçao';
UPDATE team set fifaranking = 85 WHERE team = 'Lebanon';
UPDATE team set fifaranking = 86 WHERE team = 'Guinea-Bissau';
UPDATE team set fifaranking = 87 WHERE team = 'Trinidad and Tobago';
UPDATE team set fifaranking = 88 WHERE team = 'Libya';
UPDATE team set fifaranking = 89 WHERE team = 'Estonia';
UPDATE team set fifaranking = 90 WHERE team = 'Armenia';
UPDATE team set fifaranking = 91 WHERE team = 'Cyprus';
UPDATE team set fifaranking = 92 WHERE team = 'Belarus';
UPDATE team set fifaranking = 93 WHERE team = 'Gabon';
UPDATE team set fifaranking = 94 WHERE team = 'Canada';
UPDATE team set fifaranking = 95 WHERE team = 'Faroe Islands';
UPDATE team set fifaranking = 96 WHERE team = 'Congo';
UPDATE team set fifaranking = 97 WHERE team = 'Sierra Leone';
UPDATE team set fifaranking = 98 WHERE team = 'Israel';
UPDATE team set fifaranking = 99 WHERE team = 'Mauritania';
UPDATE team set fifaranking = 100 WHERE team = 'El Salvador';
