UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Austria';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Belgium';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Bosnia and Herzegovina';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Croatia';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Czech Republic';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'England';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'France';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Germany';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Netherlands';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Norway';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Portugal';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Scotland';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Spain';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Sweden';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Switzerland';
UPDATE TEAM set fifasection = 'UEFA' WHERE team = 'Turkey';
UPDATE TEAM set fifasection = 'CONCACAF' WHERE team = 'Canada';
UPDATE TEAM set fifasection = 'CONCACAF' WHERE team = 'Curaçao';
UPDATE TEAM set fifasection = 'CONCACAF' WHERE team = 'Haiti';
UPDATE TEAM set fifasection = 'CONCACAF' WHERE team = 'Mexico';
UPDATE TEAM set fifasection = 'CONCACAF' WHERE team = 'Panama';
UPDATE TEAM set fifasection = 'CONCACAF' WHERE team = 'USA';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'Australia';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'Iran';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'Iraq';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'Japan';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'Jordan';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'Qatar';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'Saudi Arabia';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'South Korea';
UPDATE TEAM set fifasection = 'AFC' WHERE team = 'Uzbekistan';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Algeria';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Cape Verde';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Congo';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Egypt';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Ghana';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Ivory Coast';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Morocco';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Senegal';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'South Africa';
UPDATE TEAM set fifasection = 'CAF' WHERE team = 'Tunisia';
UPDATE TEAM set fifasection = 'CONMEBOL' WHERE team = 'Argentina';
UPDATE TEAM set fifasection = 'CONMEBOL' WHERE team = 'Brazil';
UPDATE TEAM set fifasection = 'CONMEBOL' WHERE team = 'Colombia';
UPDATE TEAM set fifasection = 'CONMEBOL' WHERE team = 'Ecuador';
UPDATE TEAM set fifasection = 'CONMEBOL' WHERE team = 'Paraguay';
UPDATE TEAM set fifasection = 'CONMEBOL' WHERE team = 'Uruguay';
UPDATE TEAM set fifasection = 'OFC' WHERE team = 'New Zealand';