UPDATE team set fifaranking = 2 WHERE team = 'France';
UPDATE team set fifaranking = 3 WHERE team = 'Belgium';
UPDATE team set fifaranking = 4 WHERE team = 'England';
UPDATE team set fifaranking = 6 WHERE team = 'Portugal';
UPDATE team set fifaranking = 7 WHERE team = 'Netherlands';
UPDATE team set fifaranking = 8 WHERE team = 'Spain';
UPDATE team set fifaranking = 9 WHERE team = 'Italy';
UPDATE team set fifaranking = 10 WHERE team = 'Croatia';
UPDATE team set fifaranking = 16 WHERE team = 'Germany';
UPDATE team set fifaranking = 19 WHERE team = 'Switzerland';
UPDATE team set fifaranking = 21 WHERE team = 'Denmark';
UPDATE team set fifaranking = 22 WHERE team = 'Ukraine';
UPDATE team set fifaranking = 25 WHERE team = 'Austria';
UPDATE team set fifaranking = 26 WHERE team = 'Hungary';
UPDATE team set fifaranking = 28 WHERE team = 'Poland';
UPDATE team set fifaranking = 33 WHERE team = 'Serbia';
UPDATE team set fifaranking = 36 WHERE team = 'Czech Republic';
UPDATE team set fifaranking = 39 WHERE team = 'Scotland';
UPDATE team set fifaranking = 40 WHERE team = 'Turkey';
UPDATE team set fifaranking = 46 WHERE team = 'Romania';
UPDATE team set fifaranking = 48 WHERE team = 'Slovakia';
UPDATE team set fifaranking = 57 WHERE team = 'Slovenia';
UPDATE team set fifaranking = 66 WHERE team = 'Albania';
UPDATE team set fifaranking = 75 WHERE team = 'Georgia';

UPDATE team set fifaranking = 1 WHERE team = 'Argentina';
UPDATE team set fifaranking = 5 WHERE team = 'Brazil';
UPDATE team set fifaranking = 11 WHERE team = 'United States';
UPDATE team set fifaranking = 12 WHERE team = 'Colombia';
UPDATE team set fifaranking = 14 WHERE team = 'Mexico';
UPDATE team set fifaranking = 15 WHERE team = 'Uruguay';
UPDATE team set fifaranking = 31 WHERE team = 'Ecuador';
UPDATE team set fifaranking = 32 WHERE team = 'Peru';
UPDATE team set fifaranking = 42 WHERE team = 'Chile';
UPDATE team set fifaranking = 45 WHERE team = 'Panama';
UPDATE team set fifaranking = 49 WHERE team = 'Canada';
UPDATE team set fifaranking = 52 WHERE team = 'Costa Rica';
UPDATE team set fifaranking = 54 WHERE team = 'Venezuela';
UPDATE team set fifaranking = 55 WHERE team = 'Jamaica';
UPDATE team set fifaranking = 56 WHERE team = 'Paraguay';
UPDATE team set fifaranking = 85 WHERE team = 'Bolivia';
