-- Filtered FIFA rankings (22 Dec 2025 snapshot).
UPDATE team set fifaranking = 34 WHERE team = 'Algeria';
UPDATE team set fifaranking = 2 WHERE team = 'Argentina';
UPDATE team set fifaranking = 26 WHERE team = 'Australia';
UPDATE team set fifaranking = 24 WHERE team = 'Austria';
UPDATE team set fifaranking = 8 WHERE team = 'Belgium';
UPDATE team set fifaranking = 5 WHERE team = 'Brazil';
UPDATE team set fifaranking = 27 WHERE team = 'Canada';
UPDATE team set fifaranking = 67 WHERE team = 'Cape Verde';
UPDATE team set fifaranking = 13 WHERE team = 'Colombia';
UPDATE team set fifaranking = 10 WHERE team = 'Croatia';
UPDATE team set fifaranking = 82 WHERE team = 'Curaçao';
UPDATE team set fifaranking = 23 WHERE team = 'Ecuador';
UPDATE team set fifaranking = 35 WHERE team = 'Egypt';
UPDATE team set fifaranking = 4 WHERE team = 'England';
UPDATE team set fifaranking = 3 WHERE team = 'France';
UPDATE team set fifaranking = 9 WHERE team = 'Germany';
UPDATE team set fifaranking = 72 WHERE team = 'Ghana';
UPDATE team set fifaranking = 84 WHERE team = 'Haiti';
UPDATE team set fifaranking = 20 WHERE team = 'Iran';
UPDATE team set fifaranking = 42 WHERE team = 'Ivory Coast';
UPDATE team set fifaranking = 18 WHERE team = 'Japan';
UPDATE team set fifaranking = 64 WHERE team = 'Jordan';
UPDATE team set fifaranking = 15 WHERE team = 'Mexico';
UPDATE team set fifaranking = 11 WHERE team = 'Morocco';
UPDATE team set fifaranking = 7 WHERE team = 'Netherlands';
UPDATE team set fifaranking = 87 WHERE team = 'New Zealand';
UPDATE team set fifaranking = 29 WHERE team = 'Norway';
UPDATE team set fifaranking = 30 WHERE team = 'Panama';
UPDATE team set fifaranking = 39 WHERE team = 'Paraguay';
UPDATE team set fifaranking = 6 WHERE team = 'Portugal';
UPDATE team set fifaranking = 54 WHERE team = 'Qatar';
UPDATE team set fifaranking = 60 WHERE team = 'Saudi Arabia';
UPDATE team set fifaranking = 36 WHERE team = 'Scotland';
UPDATE team set fifaranking = 19 WHERE team = 'Senegal';
UPDATE team set fifaranking = 61 WHERE team = 'South Africa';
UPDATE team set fifaranking = 22 WHERE team = 'South Korea';
UPDATE team set fifaranking = 1 WHERE team = 'Spain';
UPDATE team set fifaranking = 17 WHERE team = 'Switzerland';
UPDATE team set fifaranking = 41 WHERE team = 'Tunisia';
UPDATE team set fifaranking = 14 WHERE team = 'United States';
UPDATE team set fifaranking = 16 WHERE team = 'Uruguay';
UPDATE team set fifaranking = 50 WHERE team = 'Uzbekistan';
