INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (37, 'Switzerland', 'Poland', 'Saint-Étienne', 'Jun 25, 2016 15:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (38, 'Wales', 'Northern Ireland', 'Paris', 'Jun 25, 2016 18:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (39, 'Croatia', 'Portugal', 'Lens', 'Jun 25, 2016 21:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (40, 'France', 'Republic of Ireland', 'Lyon', 'Jun 26, 2016 15:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (41, 'Germany', 'Slovakia', 'Villeneuve-d´Ascq', 'Jun 26, 2016 18:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (42, 'Hungary', 'Belgium', 'Toulouse', 'Jun 26, 2016 21:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (43, 'Italy', 'Spain', 'Saint-Denis', 'Jun 27, 2016 18:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (44, 'England', 'Iceland', 'Nice', 'Jun 27, 2016 21:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (45, 'Poland', 'Portugal', 'Marseille', 'Jun 30, 2016 21:00', TRUE);
INSERT INTO game (gameid, team1, team2, city, starttime, kogame) VALUES (46, 'Wales', 'Belgium', 'Villeneuve-d´Ascq', 'Jul 01, 2016 21:00', TRUE);
