INSERT INTO team(team, initialgroup) VALUES('Turkey', 'A');
INSERT INTO team(team, initialgroup) VALUES('Italy', 'A');
INSERT INTO team(team, initialgroup) VALUES('Wales', 'A');
INSERT INTO team(team, initialgroup) VALUES('Switzerland', 'A');
INSERT INTO team(team, initialgroup) VALUES('Denmark', 'B');
INSERT INTO team(team, initialgroup) VALUES('Finland', 'B');
INSERT INTO team(team, initialgroup) VALUES('Belgium', 'B');
INSERT INTO team(team, initialgroup) VALUES('Russia', 'B');
INSERT INTO team(team, initialgroup) VALUES('Netherlands', 'C');
INSERT INTO team(team, initialgroup) VALUES('Ukraine', 'C');
INSERT INTO team(team, initialgroup) VALUES('Austria', 'C');
INSERT INTO team(team, initialgroup) VALUES('North Macedonia', 'C');
INSERT INTO team(team, initialgroup) VALUES('England', 'D');
INSERT INTO team(team, initialgroup) VALUES('Croatia', 'D');
INSERT INTO team(team, initialgroup) VALUES('Scotland', 'D');
INSERT INTO team(team, initialgroup) VALUES('Czech Republic', 'D');
INSERT INTO team(team, initialgroup) VALUES('Spain', 'E');
INSERT INTO team(team, initialgroup) VALUES('Sweden', 'E');
INSERT INTO team(team, initialgroup) VALUES('Poland', 'E');
INSERT INTO team(team, initialgroup) VALUES('Slovakia', 'E');
INSERT INTO team(team, initialgroup) VALUES('Hungary', 'F');
INSERT INTO team(team, initialgroup) VALUES('Portugal', 'F');
INSERT INTO team(team, initialgroup) VALUES('France', 'F');
INSERT INTO team(team, initialgroup) VALUES('Germany', 'F');
