INSERT INTO team(team, initialgroup) VALUES('Russia', 'A');
INSERT INTO team(team, initialgroup) VALUES('Saudi Arabia', 'A');
INSERT INTO team(team, initialgroup) VALUES('Egypt', 'A');
INSERT INTO team(team, initialgroup) VALUES('Uruguay', 'A');
INSERT INTO team(team, initialgroup) VALUES('Portugal', 'B');
INSERT INTO team(team, initialgroup) VALUES('Spain', 'B');
INSERT INTO team(team, initialgroup) VALUES('Morocco', 'B');
INSERT INTO team(team, initialgroup) VALUES('Iran', 'B');
INSERT INTO team(team, initialgroup) VALUES('France', 'C');
INSERT INTO team(team, initialgroup) VALUES('Australia', 'C');
INSERT INTO team(team, initialgroup) VALUES('Peru', 'C');
INSERT INTO team(team, initialgroup) VALUES('Denmark', 'C');
INSERT INTO team(team, initialgroup) VALUES('Argentina', 'D');
INSERT INTO team(team, initialgroup) VALUES('Iceland', 'D');
INSERT INTO team(team, initialgroup) VALUES('Croatia', 'D');
INSERT INTO team(team, initialgroup) VALUES('Nigeria', 'D');
INSERT INTO team(team, initialgroup) VALUES('Brazil', 'E');
INSERT INTO team(team, initialgroup) VALUES('Switzerland', 'E');
INSERT INTO team(team, initialgroup) VALUES('Costa Rica', 'E');
INSERT INTO team(team, initialgroup) VALUES('Serbia', 'E');
INSERT INTO team(team, initialgroup) VALUES('Germany', 'F');
INSERT INTO team(team, initialgroup) VALUES('Mexico', 'F');
INSERT INTO team(team, initialgroup) VALUES('Sweden', 'F');
INSERT INTO team(team, initialgroup) VALUES('South Korea', 'F');
INSERT INTO team(team, initialgroup) VALUES('Belgium', 'G');
INSERT INTO team(team, initialgroup) VALUES('Panama', 'G');
INSERT INTO team(team, initialgroup) VALUES('Tunisia', 'G');
INSERT INTO team(team, initialgroup) VALUES('England', 'G');
INSERT INTO team(team, initialgroup) VALUES('Poland', 'H');
INSERT INTO team(team, initialgroup) VALUES('Senegal', 'H');
INSERT INTO team(team, initialgroup) VALUES('Colombia', 'H');
INSERT INTO team(team, initialgroup) VALUES('Japan', 'H');
