INSERT INTO team(team,initialgroup) VALUES('Albania', 'A');
INSERT INTO team(team,initialgroup) VALUES('Austria', 'F');
INSERT INTO team(team,initialgroup) VALUES('Belgium', 'E');
INSERT INTO team(team,initialgroup) VALUES('Croatia', 'D');
INSERT INTO team(team,initialgroup) VALUES('Czech Republic', 'D');
INSERT INTO team(team,initialgroup) VALUES('England', 'B');
INSERT INTO team(team,initialgroup) VALUES('France', 'A');
INSERT INTO team(team,initialgroup) VALUES('Germany', 'C');
INSERT INTO team(team,initialgroup) VALUES('Hungary', 'F');
INSERT INTO team(team,initialgroup) VALUES('Iceland', 'F');
INSERT INTO team(team,initialgroup) VALUES('Italy', 'E');
INSERT INTO team(team,initialgroup) VALUES('Northern Ireland', 'C');
INSERT INTO team(team,initialgroup) VALUES('Poland', 'C');
INSERT INTO team(team,initialgroup) VALUES('Portugal', 'F');
INSERT INTO team(team,initialgroup) VALUES('Republic of Ireland', 'E');
INSERT INTO team(team,initialgroup) VALUES('Romania', 'A');
INSERT INTO team(team,initialgroup) VALUES('Russia', 'B');
INSERT INTO team(team,initialgroup) VALUES('Slovakia', 'B');
INSERT INTO team(team,initialgroup) VALUES('Spain', 'D');
INSERT INTO team(team,initialgroup) VALUES('Sweden', 'E');
INSERT INTO team(team,initialgroup) VALUES('Switzerland', 'A');
INSERT INTO team(team,initialgroup) VALUES('Turkey', 'D');
INSERT INTO team(team,initialgroup) VALUES('Ukraine', 'C');
INSERT INTO team(team,initialgroup) VALUES('Wales', 'B');
