UPDATE team set uefaranking = '1' WHERE team = 'Spain';
UPDATE team set uefaranking = '2' WHERE team = 'Germany';
UPDATE team set uefaranking = '3' WHERE team = 'England';
UPDATE team set uefaranking = '4' WHERE team = 'Italy';
UPDATE team set uefaranking = '5' WHERE team = 'Portugal';
UPDATE team set uefaranking = '6' WHERE team = 'France';
UPDATE team set uefaranking = '7' WHERE team = 'Russia';
UPDATE team set uefaranking = '8' WHERE team = 'Ukraine';
UPDATE team set uefaranking = '9' WHERE team = 'Belgium';
UPDATE team set uefaranking = '11' WHERE team = 'Turkey';
UPDATE team set uefaranking = '12' WHERE team = 'Switzerland';
UPDATE team set uefaranking = '13' WHERE team = 'Czech Republic';
UPDATE team set uefaranking = '15' WHERE team = 'Romania';
UPDATE team set uefaranking = '16' WHERE team = 'Austria';
UPDATE team set uefaranking = '17' WHERE team = 'Croatia';
UPDATE team set uefaranking = '18' WHERE team = 'Poland';
UPDATE team set uefaranking = '21' WHERE team = 'Sweden';
UPDATE team set uefaranking = '31' WHERE team = 'Slovakia';
UPDATE team set uefaranking = '33' WHERE team = 'Hungary';
UPDATE team set uefaranking = '35' WHERE team = 'Iceland';
UPDATE team set uefaranking = '39' WHERE team = 'Albania';
UPDATE team set uefaranking = '41' WHERE team = 'Republic of Ireland';
UPDATE team set uefaranking = '46' WHERE team = 'Northern Ireland';
UPDATE team set uefaranking = '51' WHERE team = 'Wales';
